name: talk_now
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  jitsi_meet_flutter_sdk: ^11.6.0
  share_plus: ^6.0.0
  fluttertoast: ^8.2.4
  permission_handler: ^11.3.1
  socket_io_client: ^3.1.2
  http: ^1.2.2
  flutter_webrtc: ^0.11.7
  clipboard: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
